//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int idPersona { get; set; }
        public string identificacion { get; set; }
        public string nomPersona { get; set; }
        public string ape1Persona { get; set; }
        public string ape2Persona { get; set; }
    }
}
